module.exports = {
  Echarts: require('./Echarts/Echarts.vue'),
  Form: require('./Form/Form.vue'),
  Conflict: require('./Conflict/Conflict.vue'),
  Radiation: require('./Radiation/Radiation.vue'),
  Diet: require('./Diet/Diet.vue'),
  Fruit: require('./Fruit/Fruit.vue'),
  Life: require('./Life/Life.vue'),
  Medicine: require('./Medicine/Medicine.vue'),
  Clothing: require('./Clothing/Clothing.vue'),
  Sexual: require('./Sexual/Sexual.vue'),
  Sport: require('./Sport/Sport.vue'),
  Lyingin: require('./Lyingin/Lyingin.vue'),
  Work: require('./Work/Work.vue'),
};
